In [ ]:
Introduction to numpy: 

In [ ]:
Numpy will be acting as an foundation libraries are built on top of numpy

In [ ]:
definition: numpy is majorly used in the calculation numerical data that we will be processing 

In [ ]:
most of the scientific computation will be replying up on numpy only 

In [ ]:
Installation of numpy:

In [2]:
!pip install numpy

In [ ]:
upgradation:

In [3]:
!pip install numpy------upgrade

ERROR: Could not find a version that satisfies the requirement numpy------upgrade (from versions: none)
ERROR: No matching distribution found for numpy------upgrade


In [ ]:
understanding datatype of numpy

In [ ]:
numpy will be working on datatype is array

Array---->

In [ ]:
what is diff b/w array and list?
which one do you prefer?

In [ ]:
perfomance and execution---->Array----why

In [ ]:
Reason: Internally it will be optimising the data saving space
syntax execution will be implemented fast....!

In [ ]:
matrices----> n dimensional arrays....!

In [7]:
import numpy as np

In [ ]:
req: creating an array with list  

In [8]:
array_one = np.array([1,2,3,4,5,6])

In [9]:
print(array_one)

[1 2 3 4 5 6]


In [10]:
type(array_one)

numpy.ndarray

In [11]:
numbers = [9,8,7,6]
array_two = np.array(numbers)
print(array_two)

[9 8 7 6]


In [ ]:
(x,y) x represents the no of rows,y represents no of columns 

In [13]:
array_of_zero = np.zeros((3,4))
array_of_zero

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
array_of_zero = np.ones((4,5))
array_of_zero

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [12]:
array_of_zero = np.zeros((4,5,6))
array_of_zero

array([[[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]]])