In [ ]:
Github ------->

New Repository creation : Advanced_Python ---->upload all your files to advanced python repository.
    
New Repository creation : Assignments : upload your assignment files to the Assignments repository.

In [ ]:
Practical implementation: 

In [ ]:
3rd party libraries of python:

In [ ]:
python code   1 15 lines(higher errors) |.Numpy ----4 lines --lines of code will be reduced(A lot more efficiency,with less errors in code...!)        

In [1]:
import numpy as np #shift + enter, np as alias name

In [ ]:
Datatype : Numpy is offering a data type called as an 'Array'

In [ ]:
N - Dimensional arrays (ndarray)

In [ ]:
What is the difference between an array and a list....? (Interview question)

In [ ]:
Numpy ---->  Work on Numerical computations() and also scientific computations.....! 

In [ ]:
Generic syntax of an numpy: 

In [ ]:
numpy.array(data, dtype, copy)

In [ ]:
req: passing a list to an ndarray.

In [3]:
a = np.array([1,2,3,4,5,6])

In [4]:
print(a)

[1 2 3 4 5 6]


In [5]:
type(a)

numpy.ndarray

In [6]:
array_of_zeros = np.zeros(2,3)

print(array_of_zeros)

TypeError: data type not understood

In [7]:
array_of_zeros = np.zeros([2,3])

print(array_of_zeros)

[[0. 0. 0.]
 [0. 0. 0.]]


In [8]:
array_of_zeros = np.zeros([3,4])

print(array_of_zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [9]:
array_of_zeros = np.zeros([3,4])

array_of_zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
x,y (3,4) ------> x = no. of rows and y as no. of columns 