In [20]:
import numpy as np

In [ ]:
# printing the arrays:

In [ ]:
req: to create an array of 10 numbers.....?

In [4]:
x = np.arange(10)

x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
req: using reshape to create ndimensional arrays...?2nd array....!

In [5]:
array_nd = np.arange(10).reshape(2,5)

array_nd

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [6]:
array_nd.shape # (x,y) ======> 2 dimension #3 dimension (x,y,z) =====>(1,3,5)

(2, 5)

In [7]:
array_nd = np.arange(10).reshape(3,6)

array_nd

ValueError: cannot reshape array of size 10 into shape (3,6)

In [ ]:
10.......... 2,5 #2*5 = 10

In [8]:
array_nd = np.arange(10).reshape(5,2)

array_nd

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [ ]:
# 1D (one dimensional) array:

In [14]:
a = np.arange(6)

In [11]:
print(a)

[0 1 2 3 4 5]


In [12]:
a.shape #(x) ------> 1D array

(6,)

In [ ]:
#2D array:

In [17]:
b = np.arange(12).reshape(4,3)

b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [18]:
b.shape

(4, 3)

In [ ]:
#3D array:

In [22]:
c = np.arange(24).reshape(2,3,4) #x.y.z = 24

c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [23]:
c.shape #(x,y,z)

(2, 3, 4)