In [ ]:
continuation of the numpy:

In [1]:
import numpy as np

In [ ]:
Arithametic operation of numpy:

In [2]:
a = np.array([15,15,15])
b = np.array([5,5,5])

In [3]:
a+b

array([20, 20, 20])

In [4]:
a-b

array([10, 10, 10])

In [5]:
a*b

array([75, 75, 75])

In [6]:
a/b

array([3., 3., 3.])

In [7]:
a<b  #comparison

array([False, False, False])

In [ ]:
modifying an exsisting array rather than create a new one 

In [8]:
a+=3

a

array([18, 18, 18])

In [9]:
b+=a

b

array([23, 23, 23])

In [ ]:
unary operator: 

In [11]:
ages = np.array([12,15,18,20])

In [12]:
ages.min()

12

In [13]:
ages.max()

20

In [14]:
ages.sum()

65

In [16]:
numbers = np.arange(12).reshape(3,4)

In [17]:
numbers

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
In a 2nd array--->axis=0----cols and axis=1---->rows

In [ ]:
#To get sum of each column

In [20]:
numbers.sum(axis=0)

array([12, 15, 18, 21])

In [ ]:
#To get sum of each row

In [21]:
numbers.sum(axis=1)

array([ 6, 22, 38])