In [1]:
import numpy as np

In [ ]:
Introduction to Numpy ----
understanding of the Arrays----
matrices and methods implementation ----
arrays and reshaping ----
understanding the dimensions concepts----

In [ ]:
Implementation of for loop in Numpy:

In [ ]:
Two methods:

1)flatten, and 2) nditer....! by using which we wil be implementing for loops in numpy.

In [2]:
x = np.arange(12)

x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [3]:
for a in x:
    print(a)

0
1
2
3
4
5
6
7
8
9
10
11


In [4]:
y = np.reshape(4,3)

y

ValueError: cannot reshape array of size 1 into shape (3,)

In [5]:
y = x.reshape(4,3)

y

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [6]:
for a in y:
    print(a)

[0 1 2]
[3 4 5]
[6 7 8]
[ 9 10 11]


In [ ]:
implementation of an nditer and flatten we will be seeing:

In [ ]:
flatten how it needs to implemented.